"""Initial migration

Revision ID: 395ab3513b5b
Revises: 102f05b040c3
Create Date: 2023-04-19 19:41:45.567289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '395ab3513b5b'
down_revision = '102f05b040c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('fileName', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    # ### end Alembic commands ###
